server:
  port: 8080
spring:
  application:
    name: "cleanArchitecture"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: franchises
    username: postgres
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

#logging:
#  level:
#    org.springframework.r2dbc.core: DEBUG
#    io.r2dbc.postgresql.QUERY: DEBUG

