server:
  port: ${SERVER_PORT}
spring:
  application:
    name: "cleanArchitecture"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  flyway:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${SSL_MODE}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true

adapters:
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    ssl-required: ${SSL_MODE}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  swagger-ui:
    url: swagger.yaml
#    path: /swagger-ui.html

#logging:
#  level:
#    org.springframework.r2dbc.core: DEBUG
#    io.r2dbc.postgresql.QUERY: DEBUG

